src/objects/Sandbox_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Sandbox User Custom Settings.  This custom Setting is used to see which users should be enabled when the refresh of the sandbox is complete</description>
    <fields>
        <fullName>Alias__c</fullName>
        <description>Alias</description>
        <inlineHelpText>Alias</inlineHelpText>
        <label>Alias</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address of the user</description>
        <inlineHelpText>Email address of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Encoding_Key__c</fullName>
        <label>Encoding Key</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tells if this user should be picked up for creation</description>
        <inlineHelpText>Tells if this user should be picked up for creation</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>Operation is one of these value CREATE or ENABLE.  All other users that are tagged not tagged as Create or Enable are disabled by default</description>
        <inlineHelpText>Operation is one of these value CREATE or ENABLE.  All other users that are tagged not tagged as Create or Enable are disabled by default</inlineHelpText>
        <label>Operation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sandbox Users</label>
</CustomObject>

src/classes/SandboxPostCopyUtlity_Test.cls
@isTest
private class SandboxPostCopyUtlity_Test
{

	/* Setup initial test data */
	@testSetup
	static void setUpData() {
		//Create Users
		List<User> users = new List<User>();
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
		users.add(new User(FirstName='Bob',LastName='Smith',Alias='bsi2347',
											Email='bob.smith=universalcontainers.com@example.com.dev',
											username='bob.smith@universalcontainers.com.dev',isActive=true,
											LanguageLocaleKey='en_US', LocaleSidKey='en_US',
											TimeZoneSidKey='America/New_York',ProfileId = p.Id,
											EmailEncodingKey='UTF-8'));
		users.add(new User(FirstName='Mary',LastName='Smith',Alias='mi247',
											Email='Mary.smith=universalcontainers.com@example.com',
											username='Mary.smith@universalcontainers.com.dev',isActive=true,
											LanguageLocaleKey='en_US', LocaleSidKey='en_US',
											TimeZoneSidKey='America/New_York',ProfileId = p.Id,
											EmailEncodingKey='UTF-8'));
		users.add(new User(FirstName='Joe',LastName='Smith',Alias='jdmi247',
											Email='Joe.smith=universalcontainers.com@example.com',
											username='Joe.smith@universalcontainers.com.dev',isActive=true,
											LanguageLocaleKey='en_US', LocaleSidKey='en_US',
											TimeZoneSidKey='America/New_York',ProfileId = p.Id,
											EmailEncodingKey='UTF-8'));

		insert users;

		List<Sandbox_Users__c> sandboxUsers = new List<Sandbox_Users__c>();
		sandboxUsers.add(new Sandbox_Users__c(name='bob.smith@universalcontainers.com',
										Email__c='bob.smith@universalcontainers.com',Is_Active__c=true,
										Operation__c='ENABLE'));

		sandboxUsers.add(new Sandbox_Users__c(name='mary.smith@universalcontainers.com',
																		Email__c='mary.smith@universalcontainers.com',
																		Is_Active__c=true,
																		Operation__c='ENABLE'));
		sandboxUsers.add(new Sandbox_Users__c(name='james.smith@universalcontainers.com',
																		Email__c='james.smith@universalcontainers.com',
																		Is_Active__c=true,First_Name__c='James',
																		Last_Name__c='Smith',
																		Alias__c='Smith&*&',
																		Timezone__c='America/New_York',
																		Encoding_Key__c='UTF-8',
																		Profile_Name__c='Standard User',
																		Operation__c='CREATE'));

		insert sandboxUsers;


	}


	/** Check what happens when no users are enabled or disabled the system **/
	static testMethod void testSandboxNoUsersCopy()
	{
		SandboxPostCopyUtlity spcu = new SandboxPostCopyUtlity();
		// Given
			Test.testSandboxPostCopyScript(spcu,UserInfo.getOrganizationId(), UserInfo.getOrganizationId(), 'dev');
		// When
		//TODO:  Need to write assert logic
		// Then

	}

	/** Check what happens when no users are enabled or disabled the system **/
	static testMethod void testSandboxWithUsersCopy()
	{
		SandboxPostCopyUtlity spcu = new SandboxPostCopyUtlity();
		// Given
			Test.testSandboxPostCopyScript(spcu,UserInfo.getOrganizationId(), UserInfo.getOrganizationId(), 'dev');
		// When
		//TODO:  Need to write assert logic
		// Then

	}

	/** Check what happens when no users are enabled or disabled the system **/
	static testMethod void testSandboxWithoutSandboxName()
	{
		SandboxPostCopyUtlity spcu = new SandboxPostCopyUtlity();
		try {
			Test.testSandboxPostCopyScript(spcu,UserInfo.getOrganizationId(), UserInfo.getOrganizationId(), '');
		} catch (Exception ex){
			System.assertEquals('Sandbox Name is Empty', ex.getMessage());
		}



	}
}