src/objects/Sandbox_Refresh__mdt.object
<CustomObject>
    <description>Sandbox Refreshes Metadata</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks if the Class is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_of_Execution__c</fullName>
        <description>Order of Execution</description>
        <label>Order of Execution</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Run_In_All_Sandboxes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run In All Sandboxes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sandbox_Name__c</fullName>
        <description>This is a comma separated Sandbox names.  If this field is not updated, then Run_In_All_Sandboxes to true.</description>
        <label>Sandbox Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sandbox Refresh</label>
    <pluralLabel>Sandbox Refrehes</pluralLabel>
</CustomObject>

src/classes/SandboxPostCopyUtlity.cls
/*
*  This is a Utlity Class that is called when Sandbox Copy is refreshed
* @author Kalyan Lanka
*/
public with sharing class SandboxPostCopyUtlity implements SandboxPostCopy {


	public void runApexClass(SandboxContext sc){
		String sandboxName = sc.sandboxName();

		if (String.isNotBlank(sandboxName)){
			throw new SandboxPostCopyUtlityException('Sandbox Name is Empty');
		}

		for (Sandbox_Refresh__mdt sandboxRefreshMetadata : [SELECT ID,
																	DeveloperName,
																	MasterLabel,
																	NamespacePrefix,
																	Is_Active__c,
																	Order_of_Execution__c,
																	Run_In_All_Sandboxes__c,
																	Sandbox_Name__c
																	FROM Sandbox_Refresh__mdt
																	WHERE Is_Active__c = true
																	ORDER BY Order_of_Execution__c ASC]){

				if (sandboxRefreshMetadata.Run_In_All_Sandboxes__c ||
					 (String.isNotBlank(sandboxRefreshMetadata.Sandbox_Name__c) &&
							sandboxRefreshMetadata.Sandbox_Name__c.contains(sandboxName))) {
					Type classType = Type.forName(sandboxRefreshMetadata.DeveloperName);
					SandboxRefreshAbstract sra = (SandboxRefreshAbstract) classType.newInstance();
					sra.setContext(sc);
					sra.run();
				}
		}
	}
}